spring:
  application:
    name: code-review-platform

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/codereview
    username: malini
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: your-256-bit-secret-key-change-in-production-must-be-very-long-string-for-security-purposes
  expiration: 86400000  # 24 hours in milliseconds

minio:
  url: http://${MINIO_HOST:localhost}:9000
  access-key: minioadmin
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket-name: code-files