spring:
  application:
    name: file-service

  datasource:
    url: jdbc:postgresql://localhost:5432/codereview
    username: malini
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 8
      minimum-idle: 3
      pool-name: FileHikariPool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

minio:
  url: http://${MINIO_HOST:localhost}:9000
  access-key: minioadmin
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket-name: code-files

logging:
  level:
    com.codereview.file: INFO