apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: codereview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8089"
    spec:
      containers:
        - name: notification-service
          image: code-review-platform-notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: codereview
spec:
  selector:
    app: notification-service
  ports:
    - port: 8089
      targetPort: 8089
  type: ClusterIP